apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: simcupd-development
  labels:
    app: mysql
    version: "1.0"
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: "1.0"
      environment: development
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        version: "1.0"
        environment: development
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: cupdemudb
        - name: MYSQL_USER
          value: trovix
        - name: MYSQL_PASSWORD
          value: trovix
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
