kind: Service
apiVersion: v1
metadata:
  name: simcupd-service
  namespace: simcupd-development
  labels:
    app: simcupd
    version: "1.0"
    environment: development
spec:
  selector:
    app: simcupd
    version: "1.0"
    environment: development
  type: LoadBalancer
  ports:
   - port: 8080
     targetPort: 8080
     protocol: TCP
